version: '3.4'

services:
  dloc-database:
    image: mariadb:10.4
    container_name: dloc-database
    ports: 
      - ${PORT_MYSQL}:3306
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    restart: always
    networks: ["dloc-network"]
    env_file:
      - .env
    volumes:
      - ./dloc-database:/var/lib/mysql
    healthcheck:
      test: "mysql -u${MYSQL_USER} -p${MYSQL_PASSWORD} -e 'SELECT 1'"
      interval: 1s
      timeout: 3s
      retries: 3

  dloc-server:
    image: dloc-server
    restart: always
    container_name: dloc-server
    networks: ["dloc-network"]
    build: ./dloc-server
    ports: 
      - ${PORT_SERVER}:8080
    depends_on:
      dloc-database:
        condition: service_healthy

  dloc-api:
    image: dloc-api
    restart: always
    container_name: dloc-api
    networks: ["dloc-network"]
    build: ./dloc-api
    ports: 
      - ${PORT_API}:8080
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://localhost:8080/health || exit 1" 
      interval: 1s
      timeout: 3s
      retries: 3
    depends_on:
      dloc-database:
        condition: service_healthy

  dloc-frontend:
    image: dloc-frontend
    restart: always
    container_name: dloc-frontend
    networks: ["dloc-network"]
    build: ./dloc-frontend
    depends_on:
      dloc-api:
        condition: service_healthy

  dloc-ngnix:
    image: dloc-ngnix
    restart: always
    container_name: dloc-ngnix
    networks: ["dloc-network"]
    build: ./dloc-ngnix
    ports:
      - ${PORT_NGNIX}:80
    depends_on:
      dloc-api:
        condition: service_healthy

networks:
  dloc-network:
